CREATE TABLE SOURCES_PROD.SAP.CATEGORY 
CLONE SOURCES_PROD.SAP.CATEGORY;

CREATE TABLE TRANSFORM_PROD.SALES.CATEGORY_FILTERS 
AS
SELECT *,
CASE WHEN CATEGORY_NAME = 'Electronics' THEN 'E'
     ELSE 'C' END AS CATEGORY_ABB
FROM SOURCES_PROD.SAP.CATEGORY
;
SELECT *
FROM TRANSFORM_PROD.SALES.CATEGORY_FILTERS;
