CREATE TABLE SOURCES_DEV.SAP.CATEGORY 
CLONE SOURCES_PROD.SAP.CATEGORY;

CREATE TABLE TRANSFORM_DEV.SALES.CATEGORY_FILTERS 
AS
SELECT *,
CASE WHEN CATEGORY_NAME = 'Electronics' THEN 'E'
     ELSE 'C' END AS CATEGORY_ABB
FROM SOURCES_DEV.SAP.CATEGORY
;
SELECT *
FROM TRANSFORM_DEV.SALES.CATEGORY_FILTERS;
